
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('countries').del()
    .then(function () {
      // Inserts seed entries
      return knex('countries').insert([
        { id: 1, name: 'Afghanistan', code: 'af' },
        { id: 2, name: 'Albania', code: 'al' },
        { id: 3, name: 'Algeria', code: 'dz' },
        { id: 4, name: 'American Samoa', code: 'as' },
        { id: 5, name: 'Andorra', code: 'ad' },
        { id: 6, name: 'Angola', code: 'ao' },
        { id: 7, name: 'Antigua and Barbuda', code: 'ag' },
        { id: 8, name: 'Argentina', code: 'ar' },
        { id: 9, name: 'Armenia', code: 'am' },
        { id: 10, name: 'Aruba', code: 'aw' },
        { id: 11, name: 'Australia', code: 'au' },
        { id: 12, name: 'Austria', code: 'at' },
        { id: 13, name: 'Azerbaijan', code: 'az' },
        { id: 14, name: 'Bahrain', code: 'bh' },
        { id: 15, name: 'Bahamas, The', code: 'bs' },
        { id: 16, name: 'Bangladesh', code: 'bd' },
        { id: 17, name: 'Barbados', code: 'bb' },
        { id: 18, name: 'Belarus', code: 'by' },
        { id: 19, name: 'Belgium', code: 'be' },
        { id: 20, name: 'Belize', code: 'bz' },
        { id: 21, name: 'Benin', code: 'bj' },
        { id: 22, name: 'Bermuda', code: 'bm' },
        { id: 23, name: 'Bhutan', code: 'bt' },
        { id: 24, name: 'Bolivia', code: 'bo' },
        { id: 25, name: 'Bosnia and Herzegovina', code: 'ba' },
        { id: 26, name: 'Botswana', code: 'bw' },
        { id: 27, name: 'Brazil', code: 'br' },
        { id: 28, name: 'Brunei Darussalam', code: 'bn' },
        { id: 29, name: 'Bulgaria', code: 'bg' },
        { id: 30, name: 'Burkina Faso', code: 'bf' },
        { id: 31, name: 'Burundi', code: 'bi' },
        { id: 32, name: 'Cabo Verde (Cape Verde)', code: 'cv' },
        { id: 33, name: 'Cambodia', code: 'kh' },
        { id: 34, name: 'Cameroon', code: 'cm' },
        { id: 35, name: 'Canada', code: 'ca' },
        { id: 36, name: 'Central African Republic(CAR)', code: 'cf' },
        { id: 37, name: 'Chad', code: 'td' },
        { id: 38, name: 'Chile', code: 'cl' },
        { id: 39, name: 'China (People\'s Republic of)', code: 'cn' },
        { id: 40, name: 'Colombia', code: 'co' },
        { id: 41, name: 'Comoros', code: 'km' },
        { id: 42, name: 'Congo, Democratic Republic of the', code: 'cd' },
        { id: 43, name: 'Congo, Republic of the', code: 'cg' },
        { id: 44, name: 'Cook Islands', code: 'ck' },
        { id: 45, name: 'Costa Rica', code: 'cr' },
        { id: 46, name: 'Cote d\'Ivoire (Ivory Coast)', code: 'ci' },
        { id: 47, name: 'Croatia', code: 'hr' },
        { id: 48, name: 'Cuba', code: 'cu' },
        { id: 49, name: 'Curacao', code: 'cw' },
        { id: 50, name: 'Cyprus', code: 'cy' },
        { id: 51, name: 'Czech Republic', code: 'cz' },
        { id: 52, name: 'Denmark', code: 'dk' },
        { id: 53, name: 'Djibouti', code: 'dj' },
        { id: 54, name: 'Dominica', code: 'dm' },
        { id: 55, name: 'Dominican Republic', code: 'do' },
        { id: 56, name: 'Ecuador', code: 'ec' },
        { id: 57, name: 'Egypt', code: 'eg' },
        { id: 58, name: 'El Salvador', code: 'sv' },
        { id: 59, name: 'Equatorial Guinea', code: 'gq' },
        { id: 60, name: 'Eritrea', code: 'er' },
        { id: 61, name: 'Estonia', code: 'ee' },
        { id: 62, name: 'Ethiopia', code: 'et' },
        { id: 63, name: 'Fiji', code: 'fj' },
        { id: 64, name: 'Finland', code: 'fi' },
        { id: 65, name: 'France', code: 'fr' },
        { id: 66, name: 'Gabon', code: 'ga' },
        { id: 67, name: 'Gambia, The', code: 'gm' },
        { id: 68, name: 'Georgia', code: 'ge' },
        { id: 69, name: 'Germany', code: 'de' },
        { id: 70, name: 'Ghana', code: 'gh' },
        { id: 71, name: 'Greece', code: 'gr' },
        { id: 72, name: 'Grenada', code: 'gd' },
        { id: 73, name: 'Guam', code: 'gu' },
        { id: 74, name: 'Guatemala', code: 'gt' },
        { id: 75, name: 'Guinea', code: 'gn' },
        { id: 76, name: 'Guinea - Bissau', code: 'gw' },
        { id: 77, name: 'Guyana', code: 'gy' },
        { id: 78, name: 'Haiti', code: 'ht' },
        { id: 79, name: 'Honduras', code: 'hn' },
        { id: 80, name: 'Hong Kong', code: 'hk' },
        { id: 81, name: 'Hungary', code: 'hu' },
        { id: 82, name: 'Iceland', code: 'is' },
        { id: 83, name: 'India', code: 'in' },
        { id: 84, name: 'Indonesia', code: 'id' },
        { id: 85, name: 'Iran', code: 'ir' },
        { id: 86, name: 'Iraq', code: 'iq' },
        { id: 87, name: 'Ireland', code: 'ie' },
        { id: 88, name: 'Israel', code: 'il' },
        { id: 89, name: 'Italy', code: 'it' },
        { id: 90, name: 'Jamaica', code: 'jm' },
        { id: 91, name: 'Japan', code: 'jp' },
        { id: 92, name: 'Jordan', code: 'jo' },
        { id: 93, name: 'Kazakhstan', code: 'kz' },
        { id: 94, name: 'Kenya', code: 'ke' },
        { id: 95, name: 'Kiribati', code: 'ki' },
        { id: 96, name: 'Kosovo', code: 'ko' },
        { id: 97, name: 'Kuwait', code: 'kw' },
        { id: 98, name: 'Kyrgyzstan', code: 'kg' },
        { id: 99, name: 'Laos', code: 'la' },
        { id: 100, name: 'Latvia', code: 'lv' },
        { id: 101, name: 'Lebanon', code: 'lb' },
        { id: 102, name: 'Lesotho', code: 'ls' },
        { id: 103, name: 'Liberia', code: 'lr' },
        { id: 104, name: 'Libya', code: 'ly' },
        { id: 105, name: 'Liechtenstein', code: 'li' },
        { id: 106, name: 'Lithuania', code: 'lt' },
        { id: 107, name: 'Luxembourg', code: 'lu' },
        { id: 108, name: 'Macau', code: 'mo' },
        { id: 109, name: 'Macedonia (Former Yugoslav Republic)', code: 'mk' },
        { id: 110, name: 'Madagascar', code: 'mg' },
        { id: 111, name: 'Malawi', code: 'mw' },
        { id: 112, name: 'Malaysia', code: 'my' },
        { id: 113, name: 'Maldives', code: 'mv' },
        { id: 114, name: 'Mali', code: 'ml' },
        { id: 115, name: 'Malta', code: 'mt' },
        { id: 116, name: 'Marshall Islands', code: 'mh' },
        { id: 117, name: 'Mauritania', code: 'mr' },
        { id: 118, name: 'Mauritius', code: 'mu' },
        { id: 119, name: 'Mexico', code: 'mx' },
        { id: 120, name: 'Micronesia', code: 'fm' },
        { id: 121, name: 'Moldova', code: 'md' },
        { id: 122, name: 'Monaco', code: 'mc' },
        { id: 123, name: 'Mongolia', code: 'mn' },
        { id: 124, name: 'Montenegro', code: 'me' },
        { id: 125, name: 'Morocco', code: 'ma' },
        { id: 126, name: 'Mozambique', code: 'mz' },
        { id: 127, name: 'Myanmar (Burma)', code: 'mm' },
        { id: 128, name: 'Namibia', code: 'na' },
        { id: 129, name: 'Nauru', code: 'nr' },
        { id: 130, name: 'Nepal', code: 'np' },
        { id: 131, name: 'Netherlands', code: 'nl' },
        { id: 132, name: 'Netherlands Antilles', code: 'an' },
        { id: 133, name: 'New Zealand', code: 'nz' },
        { id: 134, name: 'Nicaragua', code: 'ni' },
        { id: 135, name: 'Niger', code: 'ne' },
        { id: 136, name: 'Nigeria', code: 'ng' },
        { id: 137, name: 'North Korea', code: 'kp' },
        { id: 138, name: 'Norway', code: 'no' },
        { id: 139, name: 'Oman', code: 'om' },
        { id: 140, name: 'Pakistan', code: 'pk' },
        { id: 141, name: 'Palau', code: 'pw' },
        { id: 142, name: 'Palestine', code: 'ps' },
        { id: 143, name: 'Panama', code: 'pa' },
        { id: 144, name: 'Papua New Guinea', code: 'pg' },
        { id: 145, name: 'Paraguay', code: 'py' },
        { id: 146, name: 'Peru', code: 'pe' },
        { id: 147, name: 'Philippines', code: 'ph' },
        { id: 148, name: 'Poland', code: 'pl' },
        { id: 149, name: 'Portugal', code: 'pt' },
        { id: 150, name: 'Puerto Rico', code: 'pr' },
        { id: 151, name: 'Qatar', code: 'qa' },
        { id: 152, name: 'Romania', code: 'ro' },
        { id: 153, name: 'Russia', code: 'ru' },
        { id: 154, name: 'Rwanda', code: 'rw' },
        { id: 155, name: 'Saint Kitts and Nevis', code: 'kn' },
        { id: 156, name: 'Saint Lucia', code: 'lc' },
        { id: 157, name: 'Saint Vincent and the Grenadines', code: 'vc' },
        { id: 158, name: 'Samoa', code: 'ws' },
        { id: 159, name: 'San Marino', code: 'sm' },
        { id: 160, name: 'Sao Tome and Principe', code: 'st' },
        { id: 161, name: 'Saudi Arabia', code: 'sa' },
        { id: 162, name: 'Senegal', code: 'sn' },
        { id: 163, name: 'Serbia', code: 'rs' },
        { id: 164, name: 'Seychelles', code: 'sc' },
        { id: 165, name: 'Sierra Leone', code: 'sl' },
        { id: 166, name: 'Singapore', code: 'sg' },
        { id: 167, name: 'Slovakia', code: 'sk' },
        { id: 168, name: 'Slovenia', code: 'si' },
        { id: 169, name: 'Solomon Islands', code: 'sb' },
        { id: 170, name: 'Somalia', code: 'so' },
        { id: 171, name: 'South Africa', code: 'za' },
        { id: 172, name: 'South Korea', code: 'kr' },
        { id: 173, name: 'South Sudan', code: 'ss' },
        { id: 174, name: 'Spain', code: 'es' },
        { id: 175, name: 'Sri Lanka', code: 'lk' },
        { id: 176, name: 'Sudan', code: 'sd' },
        { id: 177, name: 'Suriname', code: 'sr' },
        { id: 178, name: 'Swaziland', code: 'sz' },
        { id: 179, name: 'Sweden', code: 'se' },
        { id: 180, name: 'Switzerland', code: 'ch' },
        { id: 181, name: 'Syria', code: 'sy' },
        { id: 182, name: 'Taiwan (Chinese Taipei)', code: 'tw' },
        { id: 183, name: 'Tajikistan', code: 'tj' },
        { id: 184, name: 'Tanzania', code: 'tz' },
        { id: 185, name: 'Thailand', code: 'th' },
        { id: 186, name: 'Timor-Leste (East Timor)', code: 'tl' },
        { id: 187, name: 'Togo', code: 'tg' },
        { id: 188, name: 'Tonga', code: 'to' },
        { id: 189, name: 'Trinidad and Tobago', code: 'tt' },
        { id: 190, name: 'Tunisia', code: 'tn' },
        { id: 191, name: 'Turkey', code: 'tr' },
        { id: 192, name: 'Turkmenistan', code: 'tm' },
        { id: 193, name: 'Tuvalu', code: 'tv' },
        { id: 194, name: 'Uganda', code: 'ug' },
        { id: 195, name: 'Ukraine', code: 'ua' },
        { id: 196, name: 'United Arab Emirates (UAE)', code: 'ae' },
        { id: 197, name: 'United Kingdom (UK)', code: 'uk' },
        { id: 198, name: 'United States of America (USA)', code: 'us' },
        { id: 199, name: 'Uruguay', code: 'uy' },
        { id: 200, name: 'US Virgin Islands', code: 'vi' },
        { id: 201, name: 'Uzbekistan', code: 'uz' },
        { id: 202, name: 'Vanuatu', code: 'vu' },
        { id: 203, name: 'Vatican City (Holy See)', code: 'va' },
        { id: 204, name: 'Venezuela', code: 've' },
        { id: 205, name: 'Vietnam', code: 'vn' },
        { id: 206, name: 'Yemen', code: 'ye' },
        { id: 207, name: 'Zambia', code: 'zm' },
        { id: 208, name: 'Zimbabwe', code: 'zw' }
      ])
    })
}
